### ISSUE TITLE
Hovering over Dependencies Lower on App

### ISSUE THREAD

**Issue by tmginzburg** [nikantonelli/PortfolioItemTimeLine#7]
Hi Nik,

We have a team using this to track a huge effort, and they love seeing dependencies on the timeline. They have identified one issue: when displaying feature dependencies, if you scroll down to the bottom and hover over a dependency, the dependency info is shown but the timeline behind it disappears until you close the dependency info box.   I'm attaching a .gif showing what we see.

Not a huge issue, but thought we'd report it for you.  Thanks!

![nikantonelli-timeline-dependency-hover-over](https://user-images.githubusercontent.com/10867992/77550800-e6338d80-6e87-11ea-9e49-91b9c688c3dc.gif)

**Comment by nikantonelli** [comment]
That's a good one! It seems that when it draws the dependency popup, it places it so far down the page, that the underlying timeline goes up off the screen. I will have to look into the placement calculation.

**Comment by nikantonelli** [comment]
I obviously didn't understand that the "setTopleft" of a box was relative to the screen, not relative to the parent container. By removing the call to this function, the popup gets left where the mouse clicked - which works quite well.

I am going to close this as my test looks OK. Let me know if it fixes it for you or not
